services:
  nginx:
    container_name: gains_nginx
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mynetwork
    volumes:
      - ./nginx:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf

  backend:
    build: ./backend
    container_name: gains_api
    ports:
      - "3000:3000"
    env_file:
      - .env  # Load environment variables
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:latest
    container_name: gains_db
    env_file:
      - .env  # load same environment variables
    volumes:
      - pgdata2:/var/lib/postgresql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

volumes:
  pgdata2:

networks:
  mynetwork:
