events { }

http {
    types {
        text/html                             html htm;
        text/css                              css;
        application/javascript                js;
        text/plain                            txt;
    }
    default_type text/plain;
    
    server {
        listen 8080;
        server_name localhost;

        location / {
            root /Users/newuser/Desktop/spring26/cs364/gains-r-us/nginx;
            index index.html;
        }
    }
}

